### ISSUE TITLE
Thunder still says raining

### ISSUE THREAD

**Issue by Aefinn** [sakura-ryoko/minihud#39]
I know you previously stated that it worked correctly but here is a screenshot from thundering weather and as you can see it says just raining (tried to take a screenshot with lightning in it but unfortunately couldn't get that but it was 100% thundering 

![2024-08-03_22 54 29](https://github.com/user-attachments/assets/5e1dbffb-0dae-45b7-b825-775e218c21b1)

**Comment by Aefinn** [comment]
You can actually see thunder roars in subtitles too

**Comment by sakura-ryoko** [comment]
The regions where the thunder happens changes depending on the Biome that you are in.  The code reads whatever Vanilla spits out; as Vanilla has actual functions that says `isRaining()` or `isThundering()`, and those are what MiniHUD is using.

Perhaps there is some other mod that is changing the behavior of the `isThundering()` output ?

Because like I said, under testing, I cannot reproduce this issue.

**Comment by Aefinn** [comment]
I was previously using mod called minihud extra that added more infolines. It showed thundering correctly. Also xaeros minimap shows thundering correctly. I don't have either of thos emods right now and it's hard to believe any of my other mods would alter that since none of them are related to weather or information like that in any way.

Oh well, thanks for the help anyway and also keeping up with these mods :)

**Comment by sakura-ryoko** [comment]
Also one thing I've noticed is that the Info Line is supposed to be telling you how `long` is left for the Raining / Thundering weather; and I do not see the timer on the screen shot.  Just make sure you have the latest versions.
